### ISSUE TITLE
Need code refactoring

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#113]
We have a lot of undocumented code and I think we should create a documentation of our code

**Comment by KMax** [comment]
I don't think that it can be seen as a separate task, because in most of the cases refactoring is never ending activity. I like that you care about the quality, but we should do it constantly.

About documenting code...I see two meaningful options: _(a)_ documenting the code at the time when you write it or _(b)_ write and structure the code in a way that makes it's self-descriptive, i.e. understandable even without documentation.

Anyway, thanks for raising the question, we should keep in mind that the quality is important and we should be looking for ways that improves our code.
