### ISSUE TITLE
Relation between simulator and platform is not created

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#53]
After many reboots the simulator the device_proxy_service can't subscribe to the simulator. Device_proxy_service has message "deviceproxyservice_1     | Something went wrong! Stop proxying to ${simulator_name}".

**Comment by Amberdr0p** [comment]
Method onError is called in NewObservationHandler. This may happen because incoming messages is missing. 
https://github.com/semiotproject/semiot-platform/blob/master/device-proxy-service-drivers/simulator/src/main/java/ru/semiot/platform/drivers/simulator/handlers/coap/NewObservationHandler.java#L49

**Comment by garayzuev** [comment]
But if I create a few meters in simulator (e.g., 5) and then I stop this simulator and run this with more meters (e.g., 15),  first of 5 meters doesn't send a their testemonies but other 10 send. Why is this happening?

**Comment by garayzuev** [comment]
All right, in finale I localaze bug: if you start simulator (or device connection) earlier when the state of device changes to "OffState" then the data from device is not proxing.
