### ISSUE TITLE
Remove button doesn't remove a device

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#57]
If I click to remove button, device is removed but when I reload page device is available.

**Comment by KMax** [comment]
Yes, because it's implemented only on the UI side, therefore device is not removed from Fuseki and other modules.

I suggest to revisit this feature in the next release, because I think such a button should be in the list of devices, but should be something associated with the appropriate device driver.

Options (_ideas are welcome_):
- we can't remove an individual device, but only all devices connected through a single device driver
- we can configure a device driver via configuration page to ignore individual devices

**Comment by soylent-grin** [comment]
See the commit above.
Suggestions are fine for me.
Lets close this issue and create another for the next version, where would be described desirable workflow?

**Comment by KMax** [comment]
I agree. Closing this issue to open a new one once we'll ready to work on it.

**Comment by KMax** [comment]
Related issue - #29.
